
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 11 19:12:13 CST 2020
//----------------------------------------------------

package analizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int closeproject = 3;
  public static final int HOME = 17;
  public static final int project = 5;
  public static final int ERROR = 19;
  public static final int folder = 4;
  public static final int comillas = 13;
  public static final int ID = 18;
  public static final int extension = 10;
  public static final int equals = 14;
  public static final int menor = 12;
  public static final int EOF = 0;
  public static final int path = 8;
  public static final int slash = 15;
  public static final int point = 16;
  public static final int error = 1;
  public static final int space = 9;
  public static final int closefolder = 2;
  public static final int file = 6;
  public static final int mayor = 11;
  public static final int name = 7;
}

