/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.CSV;
import clases.proyecto;
import clases.tabla;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class contenidocsv extends javax.swing.JPanel {

    /**
     * Creates new form contenidocsv
     */
    public contenidocsv() {
        initComponents();
        
       contenido.setText(CSV.leer());
       
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextPane();
        btn_save = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setBackground(new java.awt.Color(90, 83, 76));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setBackground(new java.awt.Color(230, 225, 239));
        contenido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        contenido.setSelectedTextColor(new java.awt.Color(94, 44, 134));
        contenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contenidoMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(contenido);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 665, 200));

        btn_save.setText("Guardar edicion");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 150, -1));

        close.setText("Cerrar");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        project.tabbepane.remove(project.tabbepane.getSelectedIndex());
    }//GEN-LAST:event_closeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        
        String txt[]=contenido.getText().split("\n");
        ArrayList<String[]> contenido=new ArrayList();
        try{
          int size=txt[0].split(",").length;
        for (int i = 0; i < txt.length; i++) {
        String [] cnt=txt[i].split(",");
        if(cnt.length==size){
            contenido.add(cnt);
        }else{
        JOptionPane.showMessageDialog(this, "verifique que el numero de valores corresponda al numero de \n columnas");
        break;
        }
        }
        if(contenido.size()==txt.length){
        String archCSV = project.absoluthepath;    
        CSV.escribir(archCSV, contenido);
         JOptionPane.showMessageDialog(this, "Archivo actualizado");
       
        }else{
          JOptionPane.showMessageDialog(this, "Archivo no actualizado");
       
        }
        }catch(ArrayIndexOutOfBoundsException e){
           JOptionPane.showMessageDialog(this, "El archivo debe tener columnas registradas");
       
        }
      
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void contenidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contenidoMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_contenidoMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JButton close;
    private javax.swing.JTextPane contenido;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
