/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import analizadorLexico.AnalizadorLexicoIDE;
import analizadorLexico.parserIde;
import analizador_ide.lexicoSql;
import analizador_ide.parserSql;
import clases.ERROR;
import clases.proyecto;
import static interfaz.project.tabbepane;
import java.io.StringReader;
import java.util.ArrayList;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class nuevo_proyecto extends javax.swing.JFrame {

    /**
     * Creates new form nuevo_proyecto
     */
    private String path;

    public nuevo_proyecto() {
        this.path = "";
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorInteger1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorInteger();
        jPanel2 = new javax.swing.JPanel();
        btn_save = new principal.MaterialButtonCircle();
        txt_folder = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_path = new principal.MaterialButtomRectangle();
        txt_file = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(182, 179, 179));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_save.setBackground(new java.awt.Color(50, 38, 121));
        btn_save.setForeground(new java.awt.Color(185, 184, 188));
        btn_save.setText("GUARDAR");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 90));
        jPanel2.add(txt_folder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 50));

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 20)); // NOI18N
        jLabel3.setText("Nombre de carpeta principal");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 1, 20)); // NOI18N
        jLabel5.setText("(opcional)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 300, 370));

        jPanel1.setBackground(new java.awt.Color(136, 59, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(243, 232, 222));
        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 215, 215));
        jLabel1.setText("Ruta de proyecto... (obligatorio)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 30));

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(239, 232, 232));
        jLabel2.setText("Archivo inicial (opcional)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btn_path.setText("ESCOGER RUTA");
        btn_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pathActionPerformed(evt);
            }
        });
        jPanel1.add(btn_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 60));
        jPanel1.add(txt_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 420));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/31TxY+VUPNL.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 280, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pathActionPerformed
        this.path = "";
        JFileChooser seleccion = new JFileChooser();
        int opcion = seleccion.showOpenDialog(null);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            this.path = seleccion.getSelectedFile().getAbsolutePath();

        }
    }//GEN-LAST:event_btn_pathActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (this.path.equals("")) {
            JOptionPane.showMessageDialog(this, "Seleccione la ruta del proyecto");
        } else {
            ArrayList<String> list = new ArrayList();
            if (!txt_file.getText().isEmpty()) {
                String columnas = "";
                boolean v = true;
                int cant = 0;
                while (v) {
                    columnas = JOptionPane.showInputDialog(this, "para parar presione cancelar", "ingrese las columnas", 2);

                    try {
                        if (columnas.isEmpty()) {
                        }

                        list.add(columnas);
                        cant++;
                    } catch (NullPointerException e) {
                        if (cant > 0) {
                            v = false;
                        } else {
                            JOptionPane.showMessageDialog(this, "Ingrese al menos una columna");

                        }
                    }

                }

            }

            String array[] = this.path.split("/");
            String rutaProyecto = this.path;
            String file = txt_file.getText();
            String folder = txt_folder.getText();
            String namePj = array[array.length - 1];
            // crear nuevo proyecto
            proyecto pj = new proyecto(namePj, rutaProyecto, file, folder);
            String estructura = pj.crearEstructura(pj);
            System.out.print(estructura);
            //iniciarlizar arrays de errores-------->
            parserIde.errorSintatico = new ArrayList();
            AnalizadorLexicoIDE.errorLexico = new ArrayList();

            //parser texto---------------------------->
            AnalizadorLexicoIDE lexico = new AnalizadorLexicoIDE(new StringReader(estructura));
            try {
                new parserIde(lexico).parse();
            } catch (Exception ex) {
            }

            // si no hay errores    
            if (parserIde.errorSintatico.isEmpty() && AnalizadorLexicoIDE.errorLexico.isEmpty()) {
                 JOptionPane.showMessageDialog(this, pj.GenerateProject(pj,estructura, list));

            } else {
                // Errores---------->    
                JOptionPane.showMessageDialog(this, "Hay errores--->");
                  String erroresLexico = "";
                  
                  getError(estructura);
            }
            //limpiar campos de texto----------->
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_saveActionPerformed
    public void limpiarCampos() {
        this.path = "";
        txt_file.setText("");
        txt_folder.setText("");
    }
   private void getError(String txt) {
        String erroresLexico = "";
        ArrayList<String> colums = new ArrayList();
        colums.add("Linea");
        colums.add("Columna");
        colums.add("Valor");
        ArrayList<String[]> rows = new ArrayList();

        for (int i = 0; i < AnalizadorLexicoIDE.errorLexico.size(); i++) {
            ERROR e = AnalizadorLexicoIDE.errorLexico.get(i);
            rows.add(new String[]{String.valueOf(e.getLinea() + 1), String.valueOf(e.getColumna()), String.valueOf(e.getValor())});
        }
        
        ArrayList<String[]> rows2 = new ArrayList();
        for (int i = 0; i < parserIde.errorSintatico.size(); i++) {
            Symbol e = parserIde.errorSintatico.get(i);
            rows2.add(new String[]{(String.valueOf(e.left)), (String.valueOf(e.right)), (String.valueOf(e.value))});

        }

        

        tabla2 t2=new tabla2();
        t2.llenar2(colums, rows,txt);
        t2.llenar1(colums, rows2);
        t2.show();

       // getError2();
       
       
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevo_proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButtomRectangle btn_path;
    private principal.MaterialButtonCircle btn_save;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorInteger evaluatorInteger1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_file;
    private javax.swing.JTextField txt_folder;
    // End of variables declaration//GEN-END:variables
}
