
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 16 11:01:54 CST 2020
//----------------------------------------------------

package analizador_ide;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 22;
  public static final int Y = 19;
  public static final int SELECT = 2;
  public static final int IGUAL = 17;
  public static final int MAI = 23;
  public static final int IN = 11;
  public static final int ALL = 26;
  public static final int END = 16;
  public static final int POINT = 10;
  public static final int ERROR = 29;
  public static final int COM = 25;
  public static final int O = 20;
  public static final int ID = 28;
  public static final int ENTER = 27;
  public static final int COMILLAS = 13;
  public static final int SPACE = 14;
  public static final int FILTRAR = 3;
  public static final int COMA = 15;
  public static final int MEI = 24;
  public static final int INSERT = 4;
  public static final int MAYOR = 21;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int VALUES = 12;
  public static final int error = 1;
  public static final int PC = 9;
  public static final int PA = 8;
  public static final int DELETE = 7;
  public static final int UPDATE = 5;
  public static final int ASIG = 6;
}

